
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: ./.env
    command: >
      sh -c "
        echo 'Waiting for postgres...'
        while ! nc -z db 5432; do
          sleep 0.1
        done
        echo 'PostgreSQL started'
        
        python manage.py migrate &&
        gunicorn let.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}
      "
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A let worker -l info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    env_file: ./.env
    restart: always

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A let flower --address=0.0.0.0 --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - celery
      - redis
    env_file: ./.env
    restart: always

volumes:
  postgres_data: