
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: ./.env
    restart: always

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
      - redis
    env_file: ./.env
    command: >
      sh -c "./wait-for-postgres.sh db && 
             python manage.py migrate &&
             gunicorn let.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}"
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A let worker -l info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    env_file: ./.env
    restart: always

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A let flower --address=0.0.0.0 --port=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - celery
      - redis
    env_file: ./.env
    restart: always

volumes:
  postgres_data: