# Generated by Django 5.0.6 on 2025-07-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=50, null=True)),
                ('program_key', models.CharField(blank=True, max_length=50, null=True)),
                ('nd_title', models.CharField(blank=True, max_length=512, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nd_key', models.CharField(blank=True, max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=512, null=True)),
                ('country_at_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('application_status', models.CharField(blank=True, max_length=100, null=True)),
                ('application_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application_created_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_updated_at', models.DateTimeField(blank=True, null=True)),
                ('heard_about_program', models.CharField(blank=True, max_length=512, null=True, verbose_name='How did you hear about this program?')),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True, verbose_name='How many years of professional experience do you have?')),
                ('terms_agreement', models.CharField(blank=True, max_length=50, null=True, verbose_name='I confirm that the information I have provided above is accurate and I agree to the terms and conditions at https://udacity.com.legal')),
                ('employer_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='If employed, what is the name of your employer?')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='Please confirm your age')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Please confirm your phone number')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Please indicate your country of nationality')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Please indicate your region in Ethiopia')),
                ('education_level', models.CharField(blank=True, max_length=512, null=True, verbose_name='What is the highest level of education you have completed?')),
                ('education_institution', models.CharField(blank=True, max_length=512, null=True, verbose_name='What is the name of your education institution')),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your current employment status?')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your field of study?')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your gender?')),
                ('primary_reason', models.TextField(blank=True, null=True, verbose_name='What is your primary reason for enrolling in this program?')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
