# Generated by Django 5.0.6 on 2025-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='company_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education_institution',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='What is the name of your education institution'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education_level',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='What is the highest level of education you have completed?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employer_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='If employed, what is the name of your employer?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='heard_about_program',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='How did you hear about this program?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nd_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
