# Generated by Django 5.0.6 on 2025-07-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_applicant_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
